# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - git clone https://github.com/hgspsz/theme.git tmp
  - cp -r tmp/* ./
  - rm -r -f tmp
  - binaries/hugo 